import type { Metadata } from "next";
import './globals.css'; 
import { inter } from "@/app/ui/fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased max-[300px]:break-all bg-neutral-950 min-h-screen`}> {children}</body>
    </html>
  );
}
