import type { Metadata } from "next";
import './globals.css'; 
import { inter } from "@/app/ui/fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.className} antialiased max-[300px]:break-all bg-gray-50 min-h-screen`}> {children}</body>
    </html>
  );
}
